services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cloudcasting_backend:${CLOUDCASTING_BACKEND_VERSION:-latest}
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CLOUDCASTING_BACKEND_HOST: 0.0.0.0


